### ISSUE TITLE
Heroku Doesn't work

### ISSUE THREAD

**Issue by muhammedfurkan** [SpEcHiDe/AnyDLBot#1]
heroku button doesn't work

**Comment by muhammedfurkan** [comment]
![screenshot_2018-11-06-11-29-09-427_com android chrome](https://user-images.githubusercontent.com/9547040/48051866-5c622200-e1b7-11e8-9f37-e3d1a3c9f65a.png)

**Comment by SpEcHiDe** [comment]
@c311at  working for me 🙄🙄🤒
