### ISSUE TITLE
Fix the error in the Filename

### ISSUE THREAD

**Issue by IamJithendra** [SpEcHiDe/AnyDLBot#23]
Please remove _ instead of . And showing %20 instead of space

By this error filename is changed and we can't give the desired filename

Since it is not a client side issue. If file name has more than 64 characters Telegram reduces the length to 64 characters and replaces spaces with _

Then alert the users with the current number of characters and it allows only 64 characters

**Comment by SpEcHiDe** [comment]
This is not a client side issue. If file name has more than 64 characters Telegram reduces the length to 64 characters and replaces spaces with _
