### ISSUE TITLE
when tries to download a video from YouTube an Error Occurred and also I was unable to upload files via URL 

### ISSUE THREAD

**Issue by IamJithendra** [SpEcHiDe/AnyDLBot#29]
When try to download a video from https://youtu.be/zJH9mLteskE it shows 
**no-one gonna help you
YouTubeDL said: ERROR: Unable to download webpage:  (caused by URLError(RemoteDisconnected('Remote end closed connection without response')))**

and same error occurred when tries to upload files from direct link

**Comment by SpEcHiDe** [comment]
you set an invalid HTTP_PROXY variable.
