### ISSUE TITLE
What codes do we add in botfather to get these..

### ISSUE THREAD

**Issue by samurmaykrr** [SpEcHiDe/AnyDLBot#39]
https://i.imgur.com/9bI8kj7.jpg
as the image shows i want to implement these commands in my bot what command do i use in botfather

**Comment by HikaruIchijyo** [comment]
@Towha use /setcommands in @botfather to set commands like that in your bot

**Comment by samurmaykrr** [comment]
ah thanks for that reply...I was asking how could i set mine to shown the commands in the original bot
