### ISSUE TITLE
could be added https://b-ok.cc and https://libgen.io download integration

### ISSUE THREAD

**Issue by muhammedfurkan** [SpEcHiDe/AnyDLBot#5]
could be added https://b-ok.cc and https://libgen.io download integration 

I am given that error:

something is wrong with the URL you gave me 🤦‍♀️. If you think this could be a bug please report on ERROR: Unable to download webpage: HTTP Error 503: Service Temporarily Unavailable (caused by <HTTPError 503: 'Service Temporarily Unavailable'>);

but @roanuedhuru_bot can be downloadable file that sites..

**Comment by SpEcHiDe** [comment]
these links should work now in @AnyDLBot 
if you press the lowest buttons that appear after sending the links.
