### ISSUE TITLE
Auth Users not working

### ISSUE THREAD

**Issue by dashchalam** [SpEcHiDe/AnyDLBot#58]
Hi.
I have just setup Tguploader , in ubuntu server. And i defined auth users in config.py. the problem is : every body can use the bot not only auth users. How can i limit access just to auth users.?
I ran this script on herku too but it does not work again

**Comment by SpEcHiDe** [comment]
you need to deploy this repo, not some random fork. Also please understand how things work instead of simply creating an issue. 
![IMG_20200409_125025_591](https://user-images.githubusercontent.com/6317196/78868523-b5934c80-7a60-11ea-9c89-65f08239ea4a.jpg)
